@root =http://202.0.94.71:3000
# @name login
 
POST {{root}}/api/pub/login
Content-Type: application/json

{
    "email":"istyak1196092ndcm@gamil.com",
    "password":"123456789"
}


###
# @name Registration
POST {{root}}/api/pub/registration
Content-Type: application/json

{
    "Name":{
        "first":"Istyaq",
        "last":"Ahmmed"
    },
    "email":"istyak1196092ndc@gamil.com",
    "password":"123456789",
    "company_name":"User Teck", 
    "mobile_no":"01705559808"

}

### #Services List

get {{root}}/api/pub/services/list
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
